name: 'Walter&Donny'
favicon: null
layout_spectrum: 0.83741
typography_spectrum: 0.36706
title: Walter and Donny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#360468'
    - '#a0a5a9'
    - '#0791f5'
    - '#0738fe'
    - '#e3e3e3'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
