analytics: {}
color:
  brandColors:
    - '#360468'
    - '#a0a5a9'
    - '#0791f5'
    - '#0738fe'
    - '#e3e3e3'
  brandStrength: 0.875
  lightness: 0.8125
  rhythmicContrast: 0.75
  saturation: 0.375
cta: {}
layout_spectrum: 1
name: Walter and Donny
opengraph: {}
purpose: []
typography_spectrum: 0.36706
