name: Walter and Donny
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36706
title: Walter and Donny Official Music Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#360468'
    - '#a0a5a9'
    - '#0791f5'
    - '#0738fe'
    - '#e3e3e3'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
