typography_spectrum: 0.55534
color:
  brandColors:
    - '#360468'
    - '#a0a5a9'
    - '#0791f5'
    - '#0738fe'
    - '#e3e3e3'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4842
analytics:
  google: UA-77162030-1
  facebook: null
  twitter: null
name: Walter and Donny
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Helplessness
    id: 92b43c48-db06-4803-b3af-b4bc40753bd6
    type: content
favicon: null
title: Walter and Donny
description: Cosmic American Music
purpose: []
